openapi: 3.0.3
info:
  title: 'Fashion Store API Documentation'
  description: 'App to sell ,rent , or buy colthes'
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/v1/admin/Categorys:
    post:
      summary: 'POST Category'
      operationId: pOSTCategory
      description: 'Creates a new Category record.'
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 996a36ca-2693-4901-9c55-7136e68d81d5
                    name: 'My new Category 234'
                    slug: my-new-Category-234
                    description: 'The second best journey ever!'
                    number_of_days: '4'
                    number_of_nights: 3
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: 996a36ca-2693-4901-9c55-7136e68d81d5
                      name:
                        type: string
                        example: 'My new Category 234'
                      slug:
                        type: string
                        example: my-new-Category-234
                      description:
                        type: string
                        example: 'The second best journey ever!'
                      number_of_days:
                        type: string
                        example: '4'
                      number_of_nights:
                        type: integer
                        example: 3
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The name has already been taken.'
                  errors:
                    name:
                      - 'The name has already been taken.'
                properties:
                  message:
                    type: string
                    example: 'The name has already been taken.'
                  errors:
                    type: object
                    properties:
                      name:
                        type: array
                        example:
                          - 'The name has already been taken.'
                        items:
                          type: string
      tags:
        - 'Admin endpoints'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                is_public:
                  type: boolean
                  description: ''
                  example: true
                name:
                  type: string
                  description: ''
                  example: totam
                description:
                  type: string
                  description: ''
                  example: et
                number_of_days:
                  type: integer
                  description: ''
                  example: 11
              required:
                - name
                - description
                - number_of_days
  '/api/v1/admin/Categorys/{Category_id}/Products':
    post:
      summary: 'POST Product'
      operationId: pOSTProduct
      description: 'Creates a new Product record.'
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 996a381e-64ca-46ba-8b51-f8279d5529ad
                    name: 'Product 1'
                    starting_date: '2023-06-15'
                    ending_date: '2023-06-20'
                    price: '99.99'
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: 996a381e-64ca-46ba-8b51-f8279d5529ad
                      name:
                        type: string
                        example: 'Product 1'
                      starting_date:
                        type: string
                        example: '2023-06-15'
                      ending_date:
                        type: string
                        example: '2023-06-20'
                      price:
                        type: string
                        example: '99.99'
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The name has already been taken.'
                  errors:
                    name:
                      - 'The name has already been taken.'
                properties:
                  message:
                    type: string
                    example: 'The name has already been taken.'
                  errors:
                    type: object
                    properties:
                      name:
                        type: array
                        example:
                          - 'The name has already been taken.'
                        items:
                          type: string
      tags:
        - 'Admin endpoints'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: optio
                starting_date:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2023-07-21T08:46:39'
                ending_date:
                  type: string
                  description: 'Must be a valid date. Must be a date after <code>starting_date</code>.'
                  example: '2071-08-06'
                price:
                  type: number
                  description: ''
                  example: 39026.83
              required:
                - name
                - starting_date
                - ending_date
                - price
    parameters:
      -
        in: path
        name: Category_id
        description: 'The ID of the Category.'
        example: fugit
        required: true
        schema:
          type: string
  '/api/v1/admin/Categorys/{Category_id}':
    put:
      summary: 'PUT Category'
      operationId: pUTCategory
      description: 'Updates new Category record.'
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 996a36ca-2693-4901-9c55-7136e68d81d5
                    name: 'My new Category 234'
                    slug: my-new-Category-234
                    description: 'The second best journey ever!'
                    number_of_days: '4'
                    number_of_nights: 3
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: 996a36ca-2693-4901-9c55-7136e68d81d5
                      name:
                        type: string
                        example: 'My new Category 234'
                      slug:
                        type: string
                        example: my-new-Category-234
                      description:
                        type: string
                        example: 'The second best journey ever!'
                      number_of_days:
                        type: string
                        example: '4'
                      number_of_nights:
                        type: integer
                        example: 3
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The name has already been taken.'
                  errors:
                    name:
                      - 'The name has already been taken.'
                properties:
                  message:
                    type: string
                    example: 'The name has already been taken.'
                  errors:
                    type: object
                    properties:
                      name:
                        type: array
                        example:
                          - 'The name has already been taken.'
                        items:
                          type: string
      tags:
        - 'Admin endpoints'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                is_public:
                  type: boolean
                  description: ''
                  example: false
                name:
                  type: string
                  description: ''
                  example: odio
                description:
                  type: string
                  description: ''
                  example: harum
                number_of_days:
                  type: integer
                  description: ''
                  example: 18
              required:
                - name
                - description
                - number_of_days
    parameters:
      -
        in: path
        name: Category_id
        description: 'The ID of the Category.'
        example: aut
        required: true
        schema:
          type: string
  /api/v1/login:
    post:
      summary: 'POST Login'
      operationId: pOSTLogin
      description: 'Login with the existing user.'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  access_token: 1|a9ZcYzIrLURVGx6Xe41HKj1CrNsxRxe4pLA2oISo
                properties:
                  access_token:
                    type: string
                    example: 1|a9ZcYzIrLURVGx6Xe41HKj1CrNsxRxe4pLA2oISo
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: 'The provided credentials are incorrect.'
                properties:
                  error:
                    type: string
                    example: 'The provided credentials are incorrect.'
      tags:
        - 'Auth endpoints'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: joshua.legros@example.net
                password:
                  type: string
                  description: ''
                  example: recusandae
              required:
                - email
                - password
      security: []
  /api/v1/products:
    get:
      summary: 'GET Category Products'
      operationId: gETCategoryProducts
      description: 'Returns paginated list of Products by category id.'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 9958e389-5edf-48eb-8ecd-e058985cf3ce
                      name: 'Product on Sunday'
                      starting_date: '2023-06-11'
                      ending_date: '2023-06-16'
                      price: '99.99'
                    -
                      id: 9958e389-5edf-48eb-8ecd-e058985cf3c2
                      name: 'Product on Tuesday'
                      starting_date: '2023-06-14'
                      ending_date: '2023-06-19'
                      price: '119.99'
                    -
                      id: 9958e389-5edf-48eb-8ecd-e058985cf3c1
                      name: 'Product on Monday'
                      starting_date: '2023-06-18'
                      ending_date: '2023-06-23'
                      price: '79.99'
                  links:
                    first: 'http://Category-api.test/api/v1/Categorys/first-Category/Products?page=1'
                    last: 'http://Category-api.test/api/v1/Categorys/first-Category/Products?page=1'
                    prev: null
                    next: null
                  meta:
                    current_page: 1
                    from: 1
                    last_page: 1
                    links:
                      -
                        url: null
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: 'http://Category-api.test/api/v1/Categorys/first-Category/Products?page=1'
                        label: '1'
                        active: true
                      -
                        url: null
                        label: 'Next &raquo;'
                        active: false
                    path: 'http://Category-api.test/api/v1/Categorys/first-Category/Products'
                    per_page: 15
                    to: 3
                    total: 3
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 9958e389-5edf-48eb-8ecd-e058985cf3ce
                        name: 'Product on Sunday'
                        starting_date: '2023-06-11'
                        ending_date: '2023-06-16'
                        price: '99.99'
                      -
                        id: 9958e389-5edf-48eb-8ecd-e058985cf3c2
                        name: 'Product on Tuesday'
                        starting_date: '2023-06-14'
                        ending_date: '2023-06-19'
                        price: '119.99'
                      -
                        id: 9958e389-5edf-48eb-8ecd-e058985cf3c1
                        name: 'Product on Monday'
                        starting_date: '2023-06-18'
                        ending_date: '2023-06-23'
                        price: '79.99'
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: 9958e389-5edf-48eb-8ecd-e058985cf3ce
                        name:
                          type: string
                          example: 'Product on Sunday'
                        starting_date:
                          type: string
                          example: '2023-06-11'
                        ending_date:
                          type: string
                          example: '2023-06-16'
                        price:
                          type: string
                          example: '99.99'
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                        example: 'http://Category-api.test/api/v1/Categorys/first-Category/Products?page=1'
                      last:
                        type: string
                        example: 'http://Category-api.test/api/v1/Categorys/first-Category/Products?page=1'
                      prev:
                        type: string
                        example: null
                      next:
                        type: string
                        example: null
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      from:
                        type: integer
                        example: 1
                      last_page:
                        type: integer
                        example: 1
                      links:
                        type: array
                        example:
                          -
                            url: null
                            label: '&laquo; Previous'
                            active: false
                          -
                            url: 'http://Category-api.test/api/v1/Categorys/first-Category/Products?page=1'
                            label: '1'
                            active: true
                          -
                            url: null
                            label: 'Next &raquo;'
                            active: false
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              example: null
                            label:
                              type: string
                              example: '&laquo; Previous'
                            active:
                              type: boolean
                              example: false
                      path:
                        type: string
                        example: 'http://Category-api.test/api/v1/Categorys/first-Category/Products'
                      per_page:
                        type: integer
                        example: 15
                      to:
                        type: integer
                        example: 3
                      total:
                        type: integer
                        example: 3
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                priceFrom:
                  type: number.
                  description: ''
                  example: '"123.45"'
                priceTo:
                  type: number.
                  description: ''
                  example: '"234.56"'
                sortBy:
                  type: string.
                  description: ''
                  example: '"price"'
                sortOrder:
                  type: string.
                  description: ''
                  example: '"asc" or "desc"'
                dateFrom:
                  type: date.
                  description: ''
                  example: '"2023-06-01"'
                dateTo:
                  type: date.
                  description: ''
                  example: '"2023-07-01"'
      security: []
    parameters:
      -
        in: path
        name: Category_slug
        description: 'Optional parameter. Category Id.'
        required: true
        schema:
          type: string
        examples:
          omitted:
            summary: 'When the value is omitted'
            value: ''
          present:
            summary: 'When the value is present'
            value: '"3"'
  '/api/v1/data/{model_name}':
    get:
      summary: ''
      operationId: getApiV1DataModel_name
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: 'The selected model name is invalid.'
                properties:
                  error:
                    type: string
                    example: 'The selected model name is invalid.'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: model_name
        description: ''
        example: nihil
        required: true
        schema:
          type: string
  /api/v1/data:
    get:
      summary: ''
      operationId: getApiV1Data
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: 'The models field is required.'
                properties:
                  error:
                    type: string
                    example: 'The models field is required.'
      tags:
        - Endpoints
      security: []
tags:
  -
    name: 'Admin endpoints'
    description: ''
  -
    name: 'Auth endpoints'
    description: ''
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
